### ISSUE TITLE
Syntax error in Shakespeare notebook

### ISSUE THREAD

**Issue by sean-fitzpatrick** [callysto/callysto-sample-notebooks#10]
In the callysto-sample-notebooks repo, I noticed that -- for me, at least -- the Shakespeare notebook isn't working correctly: I'm getting a syntax error in the very first code block. Am I doing something wrong?
![screenshot from 2018-06-11 11-49-49](https://user-images.githubusercontent.com/16246721/41248467-66adafda-6d6e-11e8-9db9-ca2103540c36.png)

**Comment by byrcyb** [comment]
For some reason `import *` got changed to just `import`. I will push the fix.
